name: Ross
favicon: null
layout_spectrum: 0.24391
typography_spectrum: 0.8618
title: Ross Kaplan-Winn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff624b'
    - '#007077'
    - '#dc0015'
    - '#f9ab33'
    - '#8a8a76'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
