name: Ross Kaplan-Winn
favicon: null
layout_spectrum: 0.729
typography_spectrum: 0.8618
title: Ross Kaplan-Winn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3d3522'
    - '#8b877a'
    - '#cde700'
    - '#ea4514'
  brandStrength: 0.761301091639325
  lightness: 0.5
  saturation: 0.41015287046320736
  rhythmicContrast: 0.5713091599754989
purpose: []
